CREATE TABLE `fixture_player_statistics` (
	`fixture_id` integer NOT NULL,
	`team_id` integer NOT NULL,
	`player_id` integer NOT NULL,
	`player_name` text NOT NULL,
	`position` text,
	`minutes` integer,
	`rating` real,
	`captain` integer,
	`substitute` integer,
	`offsides` integer,
	`shots_total` integer,
	`shots_on` integer,
	`goals` integer,
	`goals_conceded` integer,
	`assists` integer,
	`saves` integer,
	`passes_total` integer,
	`passes_key` integer,
	`passes_accuracy` real,
	`tackles` integer,
	`blocks` integer,
	`interceptions` integer,
	`duels` integer,
	`duels_won` integer,
	`dribbles_attempts` integer,
	`dribbles_success` integer,
	`dribbled_past` integer,
	`fouls_drawn` integer,
	`fouls_committed` integer,
	`yellow_cards` integer,
	`red_cards` integer,
	`penalties_won` integer,
	`penalties_committed` integer,
	`penalties_scored` integer,
	`penalties_missed` integer,
	`penalties_saved` integer,
	`updated_at` text NOT NULL,
	PRIMARY KEY(`fixture_id`, `team_id`, `player_id`)
);
--> statement-breakpoint
CREATE INDEX `idx_fixture_player_statistics_fixture` ON `fixture_player_statistics` (`fixture_id`);--> statement-breakpoint
CREATE INDEX `idx_fixture_player_statistics_player` ON `fixture_player_statistics` (`player_id`,`fixture_id`);